NVIDIA-Linux/libnvcuvid.so.550.67                   usr/lib/x86_64-linux-gnu
NVIDIA-Linux/libnvidia-opticalflow.so.550.67        usr/lib/x86_64-linux-gnu
NVIDIA-Linux/libvdpau_nvidia.so.550.67              usr/lib/x86_64-linux-gnu/vdpau
#NVIDIA-Linux/32/libnvcuvid.so.550.67                    usr/lib/x86_64-linux-gnu
#NVIDIA-Linux/32/libnvidia-opticalflow.so.550.67         usr/lib/x86_64-linux-gnu
#NVIDIA-Linux/32/libvdpau_nvidia.so.550.67               usr/lib/x86_64-linux-gnu/vdpau
