NVIDIA-Linux/libnvcuvid.so.535.54.03                   usr/lib/x86_64-linux-gnu
NVIDIA-Linux/libnvidia-opticalflow.so.535.54.03        usr/lib/x86_64-linux-gnu
NVIDIA-Linux/libvdpau_nvidia.so.535.54.03              usr/lib/x86_64-linux-gnu/vdpau
#NVIDIA-Linux/32/libnvcuvid.so.535.54.03                    usr/lib/x86_64-linux-gnu
#NVIDIA-Linux/32/libnvidia-opticalflow.so.535.54.03         usr/lib/x86_64-linux-gnu
#NVIDIA-Linux/32/libvdpau_nvidia.so.535.54.03               usr/lib/x86_64-linux-gnu/vdpau
