debian/71-nvidia.rules                                               lib/udev/rules.d
debian/80-nvidia-pm.rules                                               lib/udev/rules.d
debian/create-uvm-dev-node                                           sbin
debian/framebuffer-nvidia                                            usr/share/initramfs-tools/hooks
debian/nvidia-graphics-drivers.conf                                  lib/modprobe.d
